### ISSUE TITLE
Normalize units in benchmarks

### ISSUE THREAD

**Issue by foresmac** [juri/Parse3339#5]
Initially I was really confused because it looked like the “Unix time” version was taking way more time than the other versions that should be way slower. It took reading the benchmark tables several times before I realized some are using different units. This may be automated output, but it makes comparisons harder to do because you have to look carefully at the units and shoplift decimal places in your head.

It may also be easier to read if the data were reduced to a single table using values at perhaps p80 or p90.

**Comment by juri** [comment]
Yeah, you're not wrong. I just used whatever the Benchmark library picked automatically, but I'll see about forcing some uniformity out of it.

**Comment by juri** [comment]
I fixed the time unit in 1d524b8, now it's always nanoseconds. Ideally I'd have made it always use kilobytes for memory usage but I didn't see an option for that, and I left all the columns there too for now.
